### ISSUE TITLE
something happened to my project

### ISSUE THREAD

**Issue by jhkkhtd** [lucidworks/solr-stack#17]
hello, i am tring to compile the code by your way ,but these are something unexpect , by 3rd step  i typed “ambari-server install-mpack “ ,i can't pass ,  the screen shows that the options of 'install-mpack' is not be recongized, my version 2.7,  ,would you help me ? please,

**Comment by acesar** [comment]
@jhkkhtd what is your Ambari version and the HDP version?

Please share the output of the `install-mpack` command with the `verbose` option

```
ambari-­server install-­mpack ­­--mpack=/path/to/mpack.tar.gz --verbose
```

**Comment by jhkkhtd** [comment]
@acesar  The version of Ambari is 2.2 ,,  HDP is 2.4,,,
The output is : 
[root@vasp-manager20 solr-stack]# ambari-server install-mpack --mpack=./mpack.tar.gz --verbose
Using python  /usr/bin/python2
Usage: /usr/sbinbari-server
        {start|stop|restart|setup|setup-jce|upgrade|status|upgradestack|setup-ldap|sync-ldap|set-current|setup-security|refresh-stack-hash|backup|restore|update-host-names} [options]
        Use usr/sbin/abari-server <action> --help to get details on options available.
        Or, simply invoke ambari-server.py --help to print the options.

**Comment by acesar** [comment]
The minimum  version of ambari supported is 2.5.0
see https://github.com/lucidworks/solr-stack/blob/2.2.8/src/main/mpack/mpack.json#L7
