### ISSUE TITLE
Installation of "lucidworks-hdpsearch" Ubuntu 14.04 fails

### ISSUE THREAD

**Issue by bohyn** [lucidworks/solr-stack#18]
Installation of "lucidworks-hdpsearch" DEB package on Ubuntu 14.04 fails.
Reason is, that "/bin/sh" is alias for "/bin/dash", while "/bin/bash" is expected.

Problem is described here:
https://community.hortonworks.com/questions/114442/problems-installing-lucidworks-hdpsearch.html

Although there is a workaround using changing the default Ubuntu setting, I believe the "preinst" DEB script can be written in more compatible way.

**Comment by ctargett** [comment]
While the "lucidworks-hdpsearch" package includes this spark-solr repository, it's built by Hortonworks in partnership with Lucidworks and includes many other components. I'd suggest ensuring that this feedback and the community discussion are brought to the attention of Hortonworks Support so they can work through their channels and get it fixed for future builds.

**Comment by bohyn** [comment]
Could not reproduce issue with latest version. Closing
